name: anythingllm
services:
  anything-llm:
    container_name: anythingllm_smart_ai
    image: sokhapen/smart_ai
    volumes:
      - "./.env:/app/server/.env"
      - "../server/endpoints:/app/server/endpoints"
      - "../frontend/dist:/app/server/public"
      - "./storage:/app/server/storage"
      - "../collector/hotdir/:/app/collector/hotdir"
      - "../collector/outputs/:/app/collector/outputs"
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "3001:3001"
    cap_add:
      - SYS_ADMIN
    environment:
    # Adjust for your environment
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET="make this a large list of random numbers and letters 20+"
      - VECTOR_DB=lancedb
      - WHISPER_PROVIDER=local
      - TTS_PROVIDER=native
      - PASSWORDMINCHAR=8 
    env_file:
      - .env